---
- name: installed zsh
  yum: name=zsh state=latest

- name: users
  # python -c 'import crypt; print crypt.crypt("moongift", "$1$SomeSalt$")'
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}} shell={{item.shell}}
  with_items: users

- name: ~/.ssh for users
  file: path=/home/{{item.name}}/.ssh state=directory owner={{item.name}} group={{item.name}} mode=0700
  with_items: users

- name: configured sudo
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0440

- name: configured sshd
  notify:
    - restart sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0600

- name: running sshd
  service: name=sshd state=running enabled=yes
