- name: users exist
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}}
  with_items: users
  tags: users

- name: ~/.ssh for users exist
  file: path="/home/{{item.name}}/.ssh" state=directory owner={{item.name}} group={{item.name}} mode=0700
  with_items: users
  tags: users

- name: authorized keys is deployed
  copy: src="authorized_keys_for_{{item.name}}" dest="/home/{{item.name}}/.ssh/authorized_keys" owner={{item.name}} group={{item.name}} mode=0600
  with_items: users
  tags: users

- name: sudo configured
  copy: src="sudoers" dest="/etc/sudoers" owner=root group=root mode=0440

- name: sshd is configured
  notify:
    - restart sshd
  copy: src="sshd_config" dest="/etc/ssh/sshd_config" owner=root group=root mode=0600
  tags: sshd

- name: sshd is enabled and started
  service: name=sshd state=running enabled=yes
  tags: sshd

- name: firewalld is disabled and stoped
  service: name=firewalld state=stopped enabled=no
  tags: firewalld

- name: Docker group should exist
  group: name=docker state=present

- name: Vagrant should be a member of docker group
  user: name={{item.name}} groups=docker state=present
  with_items: users

- name: Docker should be installed
  yum: name=docker state=present

- name: Docker should be running
  service: name=docker state=started enabled=yes

- name: docker-compose command should be installed
  get_url: url=https://github.com/docker/compose/releases/download/1.5.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=755 sha256sum=5b9b6287c95103a553f8902e1e607bf4cdae74466f66a78d25195252ba380b0e
