---
- name: upgrade all packages
  yum: name=* state=latest

- name: install the latest version of zsh
  yum: name=zsh state=latest

- name: install the latest version of git
  yum: name=git state=latest

- name: add some users
  # python -c 'import crypt; print crypt.crypt("moongift", "$1$SomeSalt$")'
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}} shell={{item.shell}}
  with_items: users

- name: copy a new sudoers file
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0440

- name: copy a new sshd file
  notify:
    - restart sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0600

- name: action to enable service sshd
  service: name=sshd enabled=yes
