---
- name: install dependency php
  yum: name={{ item }} state=latest
  with_items:
    - libxml2-devel
    - openssl-devel
    - bzip2-devel
    - libmcrypt-devel
    - readline-devel
    - libxslt-devel

- name: install the latest version of php54
  yum: name={{ item }} state=latest
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-pdo
    - php-gd
