---
- name: copy a new docker.repo file
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644

- name: install the latest version of docker-engine
  yum: name=docker-engine state=latest

- name: action to enable service docker.service
  service: name=docker.service enabled=yes

- name: create the docker group.
  group: name=docker state=present

- name: users should be a member of docker group
  user: name={{ item.name }} groups={{ item.groups }} state=present
  with_items: "{{ dockerusers }}"

- name: install the docker-compose
  shell: "{{ item }}"
  with_items:
    - /usr/bin/curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - /usr/bin/chmod +x /usr/local/bin/docker-compose
