---
- name: shows the full path
  shell: which emacs
  register: pathemacs
  failed_when: pathemacs.rc not in [0, 1]

- name: download emacs
  get_url:
    url: http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-25.1.tar.gz
    dest: /usr/local/src/emacs.tar.gz
    mode: 0644
  when: pathemacs.rc == 1

- name: create a directory emacs if it doesn't exist
  file: path=/usr/local/src/emacs state=directory mode=0755
  when: pathemacs.rc == 1

- name: open a tar file emacs
  shell: tar xzvf emacs.tar.gz -C emacs --strip-components 1
  args:
    chdir: /usr/local/src
  when: pathemacs.rc == 1

- name: install dependency
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - ncurses-devel
  when: pathemacs.rc == 1

- name: install the latest version (1/3)
  command: chdir=/usr/local/src/emacs ./configure --prefix=/usr/local --without-x --with-x-toolkit=no --with-xpm=no --with-jpeg=no --with-gif=no --with-tiff=no --with-png=no --without-selinux
  when: pathemacs.rc == 1

- name: install the latest version (2/3)
  make: chdir=/usr/local/src/emacs
  when: pathemacs.rc == 1

- name: install the latest version (3/3)
  make: chdir=/usr/local/src/emacs target=install
  become: yes
  when: pathemacs.rc == 1
